version: '3.1'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: chatdb
    ports:
      - 3306:3306

  slacklikebackend-container:
    image: slacklikebackend:1
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/springboot-docker-compose-app
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/chatdb?serverTimezone=UTC
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: password
    depends_on:
      - db